-- begin TEST_AREA
alter table TEST_AREA add constraint FK_TEST_AREA_ON_PARENT_CODE foreign key (PARENT_CODE) references TEST_AREA(CODE)^
create index IDX_TEST_AREA_ON_PARENT_CODE on TEST_AREA (PARENT_CODE)^
-- end TEST_AREA
-- begin TEST_HOSPITAL
alter table TEST_HOSPITAL add constraint FK_TEST_HOSPITAL_ON_PROVINCE_CODE foreign key (PROVINCE_CODE) references TEST_AREA(CODE)^
alter table TEST_HOSPITAL add constraint FK_TEST_HOSPITAL_ON_CITY_CODE foreign key (CITY_CODE) references TEST_AREA(CODE)^
create index IDX_TEST_HOSPITAL_ON_PROVINCE_CODE on TEST_HOSPITAL (PROVINCE_CODE)^
create index IDX_TEST_HOSPITAL_ON_CITY_CODE on TEST_HOSPITAL (CITY_CODE)^
-- end TEST_HOSPITAL
