alter table TEST_HOSPITAL add constraint FK_TEST_HOSPITAL_ON_PROVINCE_CODE foreign key (PROVINCE_CODE) references TEST_AREA(CODE);
create index IDX_TEST_HOSPITAL_ON_PROVINCE_CODE on TEST_HOSPITAL (PROVINCE_CODE);
